
// This file has been generated by the GUI designer. Do not modify.
namespace EncryptionSamples
{
	public partial class StreamCipher
	{
		private global::Gtk.VBox vbox9;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label18;
		private global::Gtk.Entry entry10;
		private global::Gtk.Label label19;
		private global::Gtk.VBox vbox10;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview6;
		private global::Gtk.Label label20;
		private global::Gtk.VBox vbox11;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView textview7;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Button button25;
		private global::Gtk.Button button26;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget EncryptionSamples.StreamCipher
			this.Name = "EncryptionSamples.StreamCipher";
			this.Title = global::Mono.Unix.Catalog.GetString ("StreamCipher");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child EncryptionSamples.StreamCipher.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Key");
			this.hbox8.Add (this.label18);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label18]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry ();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '●';
			this.hbox8.Add (this.entry10);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entry10]));
			w2.Position = 1;
			this.vbox9.Add (this.hbox8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Message");
			this.vbox9.Add (this.label19);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label19]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview6 = new global::Gtk.TextView ();
			this.textview6.CanFocus = true;
			this.textview6.Name = "textview6";
			this.GtkScrolledWindow.Add (this.textview6);
			this.vbox10.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.GtkScrolledWindow]));
			w6.Position = 0;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
			this.vbox10.Add (this.label20);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label20]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview7 = new global::Gtk.TextView ();
			this.textview7.CanFocus = true;
			this.textview7.Name = "textview7";
			this.GtkScrolledWindow1.Add (this.textview7);
			this.vbox11.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.GtkScrolledWindow1]));
			w9.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button25 = new global::Gtk.Button ();
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			this.button25.UseUnderline = true;
			this.button25.Label = global::Mono.Unix.Catalog.GetString ("Encrypt");
			this.hbox9.Add (this.button25);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button25]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button26 = new global::Gtk.Button ();
			this.button26.CanFocus = true;
			this.button26.Name = "button26";
			this.button26.UseUnderline = true;
			this.button26.Label = global::Mono.Unix.Catalog.GetString ("Decrypt");
			this.hbox9.Add (this.button26);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button26]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox9.Add (this.alignment5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment5]));
			w12.Position = 2;
			w12.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("The stream cipher takes a key, k, \nand puts it into a pseudo random \ngenerator, G" +
				". then the message is\nXORed with the output from the\ngenerator.      m XOR G(k) " +
				"= c"
			);
			this.hbox9.Add (this.label2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label2]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox11.Add (this.hbox9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox9]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox10.Add (this.vbox11);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vbox11]));
			w15.Position = 2;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox10]));
			w16.Position = 2;
			this.Add (this.vbox9);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 416;
			this.Show ();
		}
	}
}
