
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Alignment alignment3;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.Table table2;
	private global::Gtk.Button button14;
	private global::Gtk.Button button15;
	private global::Gtk.Button button16;
	private global::Gtk.Button button17;
	private global::Gtk.Button button18;
	private global::Gtk.Button button19;
	private global::Gtk.Button button20;
	private global::Gtk.Button button21;
	private global::Gtk.Button button22;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.Alignment alignment4;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Encryption Samples");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.vbox1.Add (this.alignment3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment3]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox3.Add (this.alignment1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
		w2.Position = 0;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString ("XOR");
		this.table2.Add (this.button14);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.button14]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button15 = new global::Gtk.Button ();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString ("OTP");
		this.table2.Add (this.button15);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.button15]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button16 = new global::Gtk.Button ();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString ("Stream Cipher");
		this.table2.Add (this.button16);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.button16]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button17 = new global::Gtk.Button ();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button17);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.button17]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button18 = new global::Gtk.Button ();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button18);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.button18]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button19 = new global::Gtk.Button ();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button19);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.button19]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button20);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.button20]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button21 = new global::Gtk.Button ();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button21);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.button21]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button22 = new global::Gtk.Button ();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.table2.Add (this.button22);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.button22]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox3.Add (this.table2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.table2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox3.Add (this.alignment2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment2]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 2;
		w13.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		// Container child alignment4.Gtk.Container+ContainerChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("These are samples of various cryptographic features.");
		this.alignment4.Add (this.label1);
		this.vbox1.Add (this.alignment4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment4]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 2;
		w16.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 303;
		this.DefaultHeight = 281;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
